name: evently
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.6.1
dependencies:
  cloud_firestore: ^5.6.4
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.5.0
  google_sign_in: ^6.2.2
  firebase_core: ^3.12.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.2.12
  google_fonts: ^6.2.1
  intl: any
  provider: ^6.1.2
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.4
  flutter_test:
    sdk: flutter
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
