// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-xveiGeY6-GRYkf1N0htbto-rYsLx43Y',
    appId: '1:417697406670:web:510e3840a5f31bf4d07a9f',
    messagingSenderId: '417697406670',
    projectId: 'event-online-5c512',
    authDomain: 'event-online-5c512.firebaseapp.com',
    storageBucket: 'event-online-5c512.firebasestorage.app',
    measurementId: 'G-JXVG68HTVL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGr5oTaDQAcraQ9LivmQcUSWu7mjmGIC0',
    appId: '1:417697406670:android:d13f007f39529936d07a9f',
    messagingSenderId: '417697406670',
    projectId: 'event-online-5c512',
    storageBucket: 'event-online-5c512.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMoDgqmeYb97u6I3MvhrfHvGR1PQ6rKNE',
    appId: '1:417697406670:ios:7b4849b97fb38172d07a9f',
    messagingSenderId: '417697406670',
    projectId: 'event-online-5c512',
    storageBucket: 'event-online-5c512.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMoDgqmeYb97u6I3MvhrfHvGR1PQ6rKNE',
    appId: '1:417697406670:ios:7b4849b97fb38172d07a9f',
    messagingSenderId: '417697406670',
    projectId: 'event-online-5c512',
    storageBucket: 'event-online-5c512.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-xveiGeY6-GRYkf1N0htbto-rYsLx43Y',
    appId: '1:417697406670:web:ae10314caaeace6ed07a9f',
    messagingSenderId: '417697406670',
    projectId: 'event-online-5c512',
    authDomain: 'event-online-5c512.firebaseapp.com',
    storageBucket: 'event-online-5c512.firebasestorage.app',
    measurementId: 'G-GYL6LYCP4P',
  );
}
